package com.bookstore.forum;

import ch.qos.logback.classic.Level;
import ch.qos.logback.classic.Logger;
import ch.qos.logback.classic.spi.ILoggingEvent;
import ch.qos.logback.core.read.ListAppender;
import com.bookstore.forum.config.DatabaseType;
import com.bookstore.forum.config.EnabledIfDatabaseAvailable;
import com.bookstore.forum.config.TestDataSourceConfiguration;
import com.bookstore.forum.entity.PostComment;
import com.bookstore.forum.service.ForumService;
import io.hypersistence.utils.hibernate.query.QueryStackTraceLogger;
import io.hypersistence.utils.hibernate.query.SQLExtractor;
import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import jakarta.persistence.TypedQuery;
import jdk.jfr.Recording;
import jdk.jfr.consumer.RecordedEvent;
import jdk.jfr.consumer.RecordingFile;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Import;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.transaction.support.TransactionTemplate;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static com.bookstore.forum.service.ForumService.COMMENTS_WITH_POST_JPQL;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Exercises the three Hypersistence Utils query-debugging tools:
 * {@code SQLExtractor} (JPQL &rarr; real SQL), {@code QueryStackTraceLogger}
 * (which application method fired the query), and {@code JfrQueryLogger} (a JFR
 * event per query). The last two are registered together via the
 * {@code CompositeStatementInspector}.
 */
@SpringBootTest(properties = "test.database=MYSQL")
@EnabledIfDatabaseAvailable(DatabaseType.MYSQL)
@Import(TestDataSourceConfiguration.class)
@ActiveProfiles("test")
class QueryUtilitiesTest {

    private static final String TITLE = "Debugging Hibernate queries";

    @PersistenceContext
    private EntityManager entityManager;

    @Autowired
    private TransactionTemplate transactionTemplate;

    @Autowired
    private ForumService forumService;

    @BeforeEach
    public void setUp() {
        forumService.deleteAll();
        forumService.createPostWithComments(TITLE, "Great read", "Very useful");
    }

    @Test
    public void sqlExtractorRendersTheGeneratedJoin() {
        String sql = transactionTemplate.execute(status -> SQLExtractor.from(
            entityManager
                .createQuery(COMMENTS_WITH_POST_JPQL, PostComment.class)
                .setParameter("title", TITLE)
        ));

        assertTrue(sql.contains("join"), () -> "Expected a join in: " + sql);
        assertTrue(sql.contains("query_util_post_comment"), () -> "Expected the comment table in: " + sql);
        assertTrue(sql.contains("query_util_post "), () -> "Expected the joined post table in: " + sql);
    }

    @Test
    public void queryStackTraceLoggerLogsTheOriginatingApplicationFrame() {
        Logger logger = (Logger) LoggerFactory.getLogger(QueryStackTraceLogger.class);
        Level originalLevel = logger.getLevel();
        ListAppender<ILoggingEvent> appender = new ListAppender<>();
        appender.start();
        logger.addAppender(appender);
        logger.setLevel(Level.DEBUG);
        try {
            forumService.findCommentsWithPost(TITLE);
        } finally {
            logger.detachAppender(appender);
            logger.setLevel(originalLevel);
        }

        assertTrue(
            appender.list.stream()
                .map(ILoggingEvent::getFormattedMessage)
                .anyMatch(message ->
                    message.contains("was generated by Hibernate")
                        && message.contains("com.bookstore.forum.service.ForumService")),
            "Expected a stack-trace log naming the ForumService frame that fired the query");
    }

    @Test
    public void jfrQueryLoggerRecordsAQueryEvent() throws Exception {
        Path recordingFile = Files.createTempFile("query-utilities", ".jfr");
        try (Recording recording = new Recording()) {
            recording.enable("io.hypersistence.utils.hibernate.query.JfrQueryLogger$QueryEvent");
            recording.start();
            forumService.findCommentsWithPost(TITLE);
            recording.stop();
            recording.dump(recordingFile);
        }

        List<RecordedEvent> events = RecordingFile.readAllEvents(recordingFile);
        Files.deleteIfExists(recordingFile);

        assertTrue(
            events.stream().anyMatch(event ->
                event.hasField("sql")
                    && event.getString("sql") != null
                    && event.getString("sql").toLowerCase().contains("query_util_post")),
            "Expected a Hibernate JFR query event mentioning the queried tables");
    }
}
