spring.datasource.url=jdbc:mysql://localhost:3306/bookstoredb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.generate-dll=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=false

spring.sql.init.mode=always
spring.sql.init.platform=mysql

# Activating this setting will report HHH90003004 warning an exception of type:
# org.springframework.orm.jpa.JpaSystemException: setFirstResult() or setMaxResults() 
# specified with collection fetch join (in-memory pagination was about to be applied, 
# but 'hibernate.query.fail_on_pagination_over_collection_fetch' is enabled)] with root cause
# spring.jpa.properties.hibernate.query.fail_on_pagination_over_collection_fetch=true