spring.datasource.url=jdbc:postgresql://localhost:5432/bookstoredb?reWriteBatchedInserts=true
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.generate-dll=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=false

spring.sql.init.mode=always

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.jpa.properties.hibernate.jdbc.batch_size = 100
spring.jpa.properties.hibernate.generate_statistics=true

#spring.datasource.hikari.data-source-properties.reWriteBatchedInserts=true

logging.level.ROOT=DEBUG