spring.datasource.url=jdbc:mysql://localhost:3306/numberdb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.generate-dll=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=false

spring.sql.init.mode=always
spring.sql.init.platform=mysql

# Tomcat CP settings
spring.datasource.tomcat.max-wait=12000
spring.datasource.tomcat.initial-size=5
spring.datasource.tomcat.max-active=5
spring.datasource.tomcat.min-idle=5
spring.datasource.tomcat.max-idle=5
spring.datasource.tomcat.maximum-pool-size=25
spring.datasource.tomcat.default-auto-commit=true
# more settings can be added as spring.datasource.tomcat.*

spring.datasource.type=org.apache.tomcat.jdbc.pool.DataSource