spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=bookstoredb;encrypt=false
spring.datasource.username=sa
spring.datasource.password=root

spring.jpa.generate-dll=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=false

spring.sql.init.mode=always
spring.sql.init.platform=sqlserver

spring.jpa.properties.hibernate.query.in_clause_parameter_padding=true