app.datasource.url=jdbc:mysql://localhost:3306/numberdb?createDatabaseIfNotExist=true&useSSL=false
app.datasource.username=root
app.datasource.password=root

spring.jpa.generate-dll=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=false

spring.sql.init.mode=always
spring.sql.init.platform=mysql

app.datasource.partition-count=9
app.datasource.max-connections-per-partition=6
app.datasource.min-connections-per-partition=2
app.datasource.acquire-increment=5
app.datasource.idle-max-age=25
app.datasource.idle-connection-test-period=25
# more settings can be added as app.datasource.*